### ISSUE TITLE
Add a way to select the current workspace

### ISSUE THREAD

**Issue by alexdewar** [alexdewar/clockify-tui#4]
All tasks on Clockify run on a particular workspace. I don't particularly understand the details myself -- I only ever use one workspace -- but we still need to tell the API which workspace we're using.

For now, we *could* just select the first workspace in the list, but going forward, we want to make this user configurable (perhaps the user could specify workspaces by UUID in the config file?).

**Comment by TinyMarsh** [comment]
I'm taking a look at this.
